import * as React from 'react';
export type IconName =
  | "VuesaxBoldAward"
  | "VuesaxBoldBlur"
  | "VuesaxBoldBuildings2"
  | "VuesaxBoldCake"
  | "VuesaxBoldCalendar"
  | "VuesaxBoldCall"
  | "VuesaxBoldCategory"
  | "VuesaxBoldChart2_"
  | "VuesaxBoldClock"
  | "VuesaxBoldElement4"
  | "VuesaxBoldFlag"
  | "VuesaxBoldFolder2"
  | "VuesaxBoldGallery"
  | "VuesaxBoldGift"
  | "VuesaxBoldHeart"
  | "VuesaxBoldHome2"
  | "VuesaxBoldNote2_"
  | "VuesaxBoldPeople"
  | "VuesaxBoldProfile2user"
  | "VuesaxBoldSetting2"
  | "VuesaxBoldTask"
  | "VuesaxBoldTaskSquare"
  | "VuesaxBoldTickSquare"
  | "VuesaxBoldUserOctagon"
  | "VuesaxBoldUserTick"
  | "VuesaxOutlineAdd"
  | "VuesaxOutlineArchive"
  | "VuesaxOutlineArrowDown2"
  | "VuesaxOutlineArrowLeft2"
  | "VuesaxOutlineArrowRight2"
  | "VuesaxOutlineAward"
  | "VuesaxOutlineBuildings2"
  | "VuesaxOutlineCake"
  | "VuesaxOutlineCalendar2"
  | "VuesaxOutlineCall"
  | "VuesaxOutlineChart2_"
  | "VuesaxOutlineClock"
  | "VuesaxOutlineCloseCircle"
  | "VuesaxOutlineDocumentText"
  | "VuesaxOutlineEdit2"
  | "VuesaxOutlineElement3"
  | "VuesaxOutlineFilterAdd"
  | "VuesaxOutlineFlag"
  | "VuesaxOutlineFolder2"
  | "VuesaxOutlineGift"
  | "VuesaxOutlineGlobal"
  | "VuesaxOutlineHeart"
  | "VuesaxOutlineLocation"
  | "VuesaxOutlineLogout"
  | "VuesaxOutlineMoon"
  | "VuesaxOutlineMore"
  | "VuesaxOutlineNote"
  | "VuesaxOutlineNotification"
  | "VuesaxOutlinePaperclip2"
  | "VuesaxOutlinePeople"
  | "VuesaxOutlineProfile2user"
  | "VuesaxOutlineSearchNormal2"
  | "VuesaxOutlineSetting2"
  | "VuesaxOutlineSmileys"
  | "VuesaxOutlineSms"
  | "VuesaxOutlineSort"
  | "VuesaxOutlineSun2"
  | "VuesaxOutlineTag"
  | "VuesaxOutlineTickCircle"
  | "VuesaxOutlineTrash"
  | "VuesaxOutlineUserTick";
export interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName;
  size?: number | string;
}
export declare const Icon: React.FC<IconProps>;
export default Icon;
